# Page settings
#baseurl = "http://thapacoffee.netlify.com"
baseurl = "/"
title = "Thapa"
description = "Nepalese coffee farmer who produces and supply Organic Arabica Bourbon Coffee Beans. Contact us to sample our coffee from Nepal."
keywords = "nepal coffee beans, coffee from nepal"
languageCode = "en-us"
logo = "logo.png"
disqusShortname = "thapacoffee-netlify-com"

[params]
  # Meta
  author = "Peranakan Francis"
  description = 'Malaysian guy lives in Nepal working on his best effort to improve and boost the online browsing experiences for both local and foreign viewers. He is also a winner of <a href="http://www.mwa.my/2017/may/khimyan-curry-a-malaysian-born-curry-paste">Malaysia Website Award 2017</a>.'
  email = "francis.tch@gmail.com"
